steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/melaka-listener:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/melaka-listener:latest'
      - '-f'
      - 'services/listener/Dockerfile'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/melaka-listener:$SHORT_SHA'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/melaka-listener:latest'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'melaka-listener'
      - '--image'
      - 'gcr.io/$PROJECT_ID/melaka-listener:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--min-instances'
      - '1'
images:
  - 'gcr.io/$PROJECT_ID/melaka-listener:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/melaka-listener:latest'
